# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Himiten's Pages
email: 1066761470@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Embrace open source, share experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://himiten.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  himiten

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
    style: compressed

